## **NumPy :** Overview

#### _Fondamentaux sur la librairie NumPy_

🟢 `complete`

---

1. **Implémentation**
    * Construction basique
    * Auto-implémentation
2. **Propriétés**
    * Structure, forme et dimensions
    * Éléments, tailles et poids
3. **Types**
    * Constructions typées
    * Conversions
4. **Manipulations**
    * Indexation
    * Formes
5. **Opérations**
    * Arithmétique
    * Fonctionnel

**Libraries**

In [1]:
import numpy as np

---
### **1.** Implémentation

##### **1.1** - Constructions basiques

Méthode `.array()`, création de tableaux à _N-Dimensions_

In [2]:
# Vecteur :: 1 Dimension
vector = np.array([1,2,3,4,5,6])

vector

array([1, 2, 3, 4, 5, 6])

In [3]:
# Matrice :: 2 Dimensions
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
# Tenseur :: 3 Dimensions (ou plus)
list_ = [
    [ [1, 2, 3], [4, 5, 6] ],
    [ [.1, .2, .3], [.4, .5, .6] ],
    [ [.01, .02, .03], [.04, .05, .06] ]
]
tensor = np.array(list_)

tensor

array([[[1.  , 2.  , 3.  ],
        [4.  , 5.  , 6.  ]],

       [[0.1 , 0.2 , 0.3 ],
        [0.4 , 0.5 , 0.6 ]],

       [[0.01, 0.02, 0.03],
        [0.04, 0.05, 0.06]]])

##### **1.2** - Auto-implémentation

Méthodes `np.arange(start, end, step)`

In [5]:
# Generate a n-elements vector with integers stepped by 2 between 0 and 10 (incl. only if allowed by the step size)
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [6]:
# Generate a 10-elements vector with integers from 0 to 10 (exclude)
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Méthodes `np.linspace(start, end, qty)`

In [7]:
# Generate a 5 elements vector linearly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

Méthodes `np.eye(shape)`

In [8]:
# Generate a squared matrix of shape 3 with diagonal 1 and 0 elsewhere
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Méthodes `np.random.random((n,m))`

In [9]:
# Generate 3*4 matrix of floatin' numbers between 0 and 1
np.random.random((3,4))

array([[0.8493958 , 0.12023347, 0.80227761, 0.02684754],
       [0.02785976, 0.8632828 , 0.15479345, 0.73242922],
       [0.39127243, 0.9125344 , 0.80999308, 0.37761428]])

---
### **2.** Propriétés

##### **2.1** - Structure, formes et dimensions

Propriété `.shape`

In [47]:
# Return tuple of axe lengths : axis 0 = n, axis 1 = m, and so on...
display( 
    tensor.shape,
    matrix.shape,
    vector.shape
)

(3, 2, 3)

(3, 3)

(6,)

Propriété `.ndim`

In [46]:
# Total of dimensions
display( 
    tensor.ndim,
    matrix.ndim,
    vector.ndim
)

3

2

1

##### **2.2** - Éléments, tailles et poids

Propriété `.dtype`

In [12]:
# Type of elements in an array
display( np.array(['Hello', -7, 1.2, True]).dtype )
np.array([-5, -3, -2, -1]).dtype

dtype('<U32')

dtype('int32')

Propriété `.size`

In [45]:
# Quantity of elements
display( 
    tensor.size,
    matrix.size,
    vector.size
)

18

9

6

Propriété `.nbytes`

In [44]:
# Total bytes of an array
display( 
    tensor.nbytes,
    matrix.nbytes,
    vector.nbytes
)

144

36

24

Propriété `.itemsize`

In [43]:
# Total bytes of individual element
display( 
    tensor.itemsize,
    matrix.itemsize,
    vector.itemsize
)

8

4

4

---
### **3.** Types

Paramètre `dtypes` du constructeur

##### **3.1** - Constructions typées

Integers `np.int_`

In [19]:
# Floating numbers truncated, and boolean as 1 or 0
integers = np.array([-4.55, -0.90, 0, 17.1, '42', True, False], dtype=np.int_)
integers

array([-4,  0,  0, 17, 42,  1,  0])

In [38]:
# Auto-conversion failed 
fail_i = np.array(["Will", "raise", "an", "error"], dtype=np.int_)
fail_i

ValueError: invalid literal for int() with base 10: 'Will'

Virgules flottantes `np.float_`

In [22]:
# Converted to floating point numbers
floats = np.array([1, 2, '3.07', 4.5, True], dtype=np.float_)
floats

array([1.  , 2.  , 3.07, 4.5 , 1.  ])

Booléen `np.bool_`

In [23]:
# Converted as Truthy / Falsy values in Python
bools = np.array([0, 1, "2", 3.5, True], dtype=np.bool_)
bools

array([False,  True,  True,  True,  True])

Texts `np.str_`

In [25]:
# Everything can be a string...
strings = np.array(['Hello', 'World', '!', 42, True], dtype=np.str_)
strings

array(['Hello', 'World', '!', '42', 'True'], dtype='<U5')

##### **3.2** - Conversions

Fonction `.astype()`

In [42]:
numbers = np.arange(2, 48, 4)
texts = numbers.astype(np.str_) # copy=False for 'inplace' convertion

display( texts.dtype, texts )

dtype('<U11')

array(['2', '6', '10', '14', '18', '22', '26', '30', '34', '38', '42',
       '46'], dtype='<U11')

---
### **4.** Manipulations

##### **4.1** - Indexation

Accès `[i]`

In [78]:
# Remind
display(
    tensor,
    matrix,
    vector
)

array([[[1.  , 2.  , 3.  ],
        [4.  , 5.  , 6.  ]],

       [[0.1 , 0.2 , 0.3 ],
        [0.4 , 0.5 , 0.6 ]],

       [[0.01, 0.02, 0.03],
        [0.04, 0.05, 0.06]]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

array([1, 2, 3, 4, 5, 6])

In [77]:
# Access to 2nd element from root of object
display(
    tensor[1], # 2nd matrix
    matrix[1], # 2nd row
    vector[1] # 2 item
)

array([[0.1, 0.2, 0.3],
       [0.4, 0.5, 0.6]])

array([4, 5, 6])

2

In [83]:
# Acces in depth
display(
    tensor[1,0], # 1rst row in 2nd matrix
    matrix[1,0] # 1rst item in 2nd row
)

array([0.1, 0.2, 0.3])

4

In [84]:
# And so on as dimension as possible...
tensor[1, 0, 2] # 3rd item, in 1rst row, in 2nd matrix

0.3

Plages `[i:j]`, `[:i]`, `[i:]`, `[::i]`

In [89]:
# With vector
vect24 = np.arange(24)
vect24

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [90]:
# From 3rd (incl.) item to 16 (excl.)
vect24[3:16]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [91]:
# 10 first items
vect24[:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [92]:
# All last items from 10th
vect24[10:]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [95]:
# All items stepped by 4
vect24[::4]

array([ 0,  4,  8, 12, 16, 20])

In [96]:
# All items stepped by 4 begin at 2nd position
vect24[2::4]

array([ 2,  6, 10, 14, 18, 22])

In [97]:
# With tensor
tens48 = np.arange(48).reshape(3, 4, 4)
tens48

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]]])

In [98]:
# From 2nd (incl.) to 4th (excl.) in all matrices
tens48[:, 1:3]

array([[[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[20, 21, 22, 23],
        [24, 25, 26, 27]],

       [[36, 37, 38, 39],
        [40, 41, 42, 43]]])

In [99]:
# From 2nd (incl.) to 4th (excl.) in 2nd matrix
tens48[1, 1:3]

array([[20, 21, 22, 23],
       [24, 25, 26, 27]])

In [100]:
# And so on...
tens48[::2, 2, :2]

array([[ 8,  9],
       [40, 41]])

##### **4.2** - Transformations

Forme `.reshape(n,)`

In [103]:
# From tensor to vector
display(
    tensor.shape,
    tensor.size 
)

# So reshape with 18 items
tensor_to_vector = tensor.reshape(18)

display(
    tensor_to_vector.shape,
    tensor_to_vector.size
)

tensor_to_vector

(3, 2, 3)

18

(18,)

18

array([1.  , 2.  , 3.  , 4.  , 5.  , 6.  , 0.1 , 0.2 , 0.3 , 0.4 , 0.5 ,
       0.6 , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06])

In [106]:
# From vector to tensor
display( 
    tensor_to_vector.shape,
    tensor_to_vector.size
)

# So reshape with factors of 18
vector_to_tensor = tensor_to_vector.reshape(3, 3, 2)

display(
    vector_to_tensor.shape,
    vector_to_tensor.size
)

vector_to_tensor

(18,)

18

(3, 3, 2)

18

array([[[1.  , 2.  ],
        [3.  , 4.  ],
        [5.  , 6.  ]],

       [[0.1 , 0.2 ],
        [0.3 , 0.4 ],
        [0.5 , 0.6 ]],

       [[0.01, 0.02],
        [0.03, 0.04],
        [0.05, 0.06]]])

---
### **5.** Opérations

##### **5.1** - Arithmétique

Les opérateurs arithmétiques permettent également les raccourcis syntaxiques _d'opérations-assignations_ –  `+=`, `*=`, etc – si le tableau de destination **est du type adéquat**.

Par exemple, une _division-assignation_ sur un tableau de type `int` lèvera une erreur car **la conversion n'est pas automatique**.

Opérateurs `+ , - , * , / , // , % , **`

In [35]:
# Classic vector operations (no loop required)
a = np.array([14, 23, 32, 41])
b = np.array([5,  4,  3,  2])

display( f"a + b  = {a + b}" )
display( f"a - b  = {a - b}" )
display( f"a * b  = {a * b}" )
display( f"a / b  = {a / b}" )
display( f"a // b  = {a // b}" )
display( f"a % b  = {a % b}" )
display( f"a ** b = {a ** b}" )

'a + b  = [19 27 35 43]'

'a - b  = [ 9 19 29 39]'

'a * b  = [70 92 96 82]'

'a / b  = [ 2.8         5.75       10.66666667 20.5       ]'

'a // b  = [ 2  5 10 20]'

'a % b  = [4 3 2 1]'

'a ** b = [537824 279841  32768   1681]'

Additions et soustractions de `matrix`

In [36]:
# Same dimensions required !
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[7,8,9],[10,11,12]])
C_add = A + B
C_add

array([[ 8, 10, 12],
       [14, 16, 18]])

In [37]:
# Idem for substractions
C_sub = A - B
C_sub

array([[-6, -6, -6],
       [-6, -6, -6]])

In [39]:
# Will raise an error
Z = np.array([[1,2,3],[4,5,6]])
Y = np.array([[7,8],[10,11]])
X_err = Z + Y
X_err

ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

Multiplication et division de `matrix`

In [40]:
# Multiplication by scalar
C_scalar = A * 2
C_scalar

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [52]:
# Shape destination is 2 * 2
M = np.array([[1,2,3],[4,5,6]])
N = np.array([[1,2],[3,4],[5,6]])

display( M.shape, N.shape )

O_dot = M.dot(N)
O_dot

(2, 3)

(3, 2)

array([[22, 28],
       [49, 64]])

In [54]:
# Will raise an error because column number of A does not match the line names of B
display( A.shape, B.shape )

D_err = A.dot(B)
D_err

(2, 3)

(2, 3)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [56]:
# Fix shape problems with transposition T
BT = B.T
display( BT.shape )

D_dot = A.dot(BT)
D_dot

(3, 2)

array([[ 50,  68],
       [122, 167]])

##### **5.2** - Broadcasting

**Règle 1**

In [59]:
h = np.arange(5).reshape(1, 1, 5)
display( h.shape )
h

(1, 1, 5)

array([[[0, 1, 2, 3, 4]]])

In [61]:
# Same as : h + [[[10, 20, 30, 40, 50]]]
h + [10, 20, 30, 40, 50]

array([[[10, 21, 32, 43, 54]]])

**Règle 2**

In [62]:
k = np.arange(6).reshape(2, 3)
display( k.shape )
k

(2, 3)

array([[0, 1, 2],
       [3, 4, 5]])

In [64]:
# Same as : k + [[100, 100, 100], [200, 200, 200]]
k + [[100], [200]]

array([[100, 101, 102],
       [203, 204, 205]])

Combinaisons

In [65]:
# After rule 1 : [[100, 200, 300]], and after rule 2: [[100, 200, 300], [100, 200, 300]]
k + [100, 200, 300]

array([[100, 201, 302],
       [103, 204, 305]])

In [66]:
# Same as : k + [[1000, 1000, 1000], [1000, 1000, 1000]]
k + 1000

array([[1000, 1001, 1002],
       [1003, 1004, 1005]])

##### **5.3** - Fonctions

Méthodes `mean()`, `.min()`, `.max()`, `.sum()`, `.prod()`, `.std()`, `.var()`

In [71]:
# Exmple with mean()
MAT = np.array([[-2.5, 3.1, 7], [10, 11, 12]])
display( MAT )
MAT.mean()

array([[-2.5,  3.1,  7. ],
       [10. , 11. , 12. ]])

6.766666666666667

In [72]:
# All at once :P
for stat in (MAT.min, MAT.max, MAT.sum, MAT.prod, MAT.std, MAT.var):
    print(stat.__name__, " = ", stat())

min  =  -2.5
max  =  12.0
sum  =  40.6
prod  =  -71610.0
std  =  5.084835843520964
var  =  25.855555555555554


Axes de travail `axis=`

In [73]:
TENS = np.arange(24).reshape(2,3,4)
TENS

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [74]:
# Across the matrices : Sum of the 2 matrices, 0 + 12, 1 + 13, 2 + 14, and so on...
TENS.sum(axis=0)

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [75]:
# Across the rows : Sum of 'columns' in each matrix, 0 + 4 + 8, 1 + 5 + 9, and so on...
TENS.sum(axis=1)

array([[12, 15, 18, 21],
       [48, 51, 54, 57]])

In [76]:
# Across matrices and columns
TENS.sum(axis=(0,2))

array([ 60,  92, 124])

---

**À suivre :**
* Créations 
* Indexation 
* Datatype
* Broadcasting